server:
  port: 9010
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: products
    enabled: false
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/havelock/Web_Shop_Project_Back-end/target/Shop_h2_db'
  jpa:
    hibernate:
      ddl-auto: update
